/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Light mode (default) ── */
        "surface-container":          "var(--color-surface-container, #edeeef)",
        "secondary-container":        "var(--color-secondary-container, #c2edcd)",
        "on-surface":                 "var(--color-on-surface, #191c1d)",
        "outline-variant":            "var(--color-outline-variant, #bdcabe)",
        "on-primary-fixed-variant":   "var(--color-on-primary-fixed-variant, #00522f)",
        "on-tertiary-container":      "var(--color-on-tertiary-container, #fffffa)",
        "surface":                    "var(--color-surface, #f8f9fa)",
        "primary-container":          "var(--color-primary-container, #008751)",
        "background":                 "var(--color-background, #f8f9fa)",
        "tertiary-container":         "var(--color-tertiary-container, #008846)",
        "on-secondary-fixed":         "var(--color-on-secondary-fixed, #002110)",
        "tertiary-fixed":             "var(--color-tertiary-fixed, #60ff99)",
        "surface-container-lowest":   "var(--color-surface-container-lowest, #ffffff)",
        "surface-tint":               "var(--color-surface-tint, #006d40)",
        "error-container":            "var(--color-error-container, #ffdad6)",
        "inverse-surface":            "var(--color-inverse-surface, #2e3132)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #294e37)",
        "secondary-fixed":            "var(--color-secondary-fixed, #c2edcd)",
        "surface-dim":                "var(--color-surface-dim, #d9dadb)",
        "on-primary-container":       "var(--color-on-primary-container, #fdfff9)",
        "secondary":                  "var(--color-secondary, #40674e)",
        "on-tertiary-fixed-variant":  "var(--color-on-tertiary-fixed-variant, #005228)",
        "tertiary-fixed-dim":         "var(--color-tertiary-fixed-dim, #00e479)",
        "primary-fixed":              "var(--color-primary-fixed, #8df8b7)",
        "on-primary":                 "var(--color-on-primary, #ffffff)",
        "surface-container-low":      "var(--color-surface-container-low, #f3f4f5)",
        "on-primary-fixed":           "var(--color-on-primary-fixed, #002110)",
        "on-error-container":         "var(--color-on-error-container, #93000a)",
        "on-tertiary-fixed":          "var(--color-on-tertiary-fixed, #00210c)",
        "surface-variant":            "var(--color-surface-variant, #e1e3e4)",
        "tertiary":                   "var(--color-tertiary, #006c36)",
        "error":                      "var(--color-error, #ba1a1a)",
        "on-secondary":               "var(--color-on-secondary, #ffffff)",
        "primary":                    "var(--color-primary, #006b3f)",
        "on-tertiary":                "var(--color-on-tertiary, #ffffff)",
        "on-error":                   "var(--color-on-error, #ffffff)",
        "surface-bright":             "var(--color-surface-bright, #f8f9fa)",
        "on-secondary-container":     "var(--color-on-secondary-container, #466d54)",
        "primary-fixed-dim":          "var(--color-primary-fixed-dim, #70db9d)",
        "surface-container-highest":  "var(--color-surface-container-highest, #e1e3e4)",
        "surface-container-high":     "var(--color-surface-container-high, #e7e8e9)",
        "inverse-primary":            "var(--color-inverse-primary, #70db9d)",
        "inverse-on-surface":         "var(--color-inverse-on-surface, #f0f1f2)",
        "on-surface-variant":         "var(--color-on-surface-variant, #3e4a41)",
        "on-background":              "var(--color-on-background, #191c1d)",
        "outline":                    "var(--color-outline, #6e7a70)",
        "secondary-fixed-dim":        "var(--color-secondary-fixed-dim, #a6d0b2)",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
